### ISSUE TITLE
Tests are very slow due to big file downloads

### ISSUE THREAD

**Issue by danielolsen** [Breakthrough-Energy/PreREISE#145]
On a pretty good home internet connection, with nothing else going on:
- **prereise/gather/demanddata/nrel_efs/tests/test_get_efs_data.py::test_download_flexibility_data** takes >2 minutes
- **prereise/gather/demanddata/nrel_efs/tests/test_get_efs_data.py::test_download_demand_data** takes >1 minute
- no other tests take more than 10 seconds

Can we cut this time down somehow, perhaps by testing the download functionality on smaller files?

**Comment by lanesmith218** [comment]
Yeah, the files are pretty large so downloading and extracting takes a while. I could write tests for the private functions (e.g., `_download_data`, `_extract_data`) instead. This should allow us to test the functionality on smaller files.
