### ISSUE TITLE
Wind/Solar/Hydro Profiles

### ISSUE THREAD

**Issue by LFPower** [Breakthrough-Energy/PreREISE#161]
Currently program for wind/solar/hydro profiles can only work for base_grid dataset.  The new user can not take advantage the powerful program to automatic populate the profiles.  The key issue is in these plant.csv there is no actual location information about the plants.  Although the plant id is unique, it is impossible to obtain the wind/solar/hydro profile based the plant id.  Since the users will have their own plant.csv in which the plant ids will be indexed by the users themselves.  In summary, it would be good that the plant.csv provides the detail power plant information and the wind/solar/hydro profile program can use these information to populate the profiles and return the user's plant id in the profile instead of the base_grid plant ids.  Currently, we observe that the profile program will return the base_grid plant ids whatever the plant.csv is.

**Comment by rouille** [comment]
The plant attribute of the Grid object, which is a pandas.DataFrame has a lat and lon columns. These columns don't come from the plant.csv as you pointed out but from the sub.csv file. I believe the functions used to generate the profiles take a Grid object and hence have access to the GPS coordinates of the plants.

**Comment by LFPower** [comment]
Current HIFLD parser can provide the sub.csv with GPS coordinates. However, we still see the plant ids in the profiles are the id in the base-grid dataset not the the one we used in HIFLD dataset.

**Comment by rouille** [comment]
Can you copy and paste here the code that prepares the input parameter for the function?

**Comment by LFPower** [comment]
I find the problem.  I need to replace the csv files under the network/usa_tamu/.   In the future, we may need provide a interface that where the user can indicate the input folder when using the function as follows:

from powersimdata.input.grid import Grid
from prereise.gather.winddata.rap import rap, impute, helpers

print("wind data population")
electricity_grid = Grid("Texas")

**Comment by rouille** [comment]
> I find the problem.  I need to replace the csv files under the network/usa_tamu/.   In the future, we may need to provide a interface that where the user can indicate the input folder when using the function as follows:
> 
> 
> 
> from powersimdata.input.grid import Grid
> 
> from prereise.gather.winddata.rap import rap, impute, helpers
> 
> 
> 
> print("wind data population")
> 
> electricity_grid = Grid("Texas")

We need to do a little refactoring of the Grid object. You can see in the constructor of the class that there is a grid_model parameter. We have to develop the if/else logic in the constructor and introduce a HIFLD class or if a parent Model class and have TAMU and HIFLD being its child since RAMU and HIFLD will be practically the same.

**Comment by danielolsen** [comment]
We have a work-in-progress branch currently in PowerSimData (`daniel/read_hifld_grid`) that can load data from the `network/hifld/data` folder, if all the required CSVs are there and they have the appropriate columns, etc. As @rouille mentioned, the `grid_model` parameter controls which location we use to grab data when building a fresh Grid from CSVs; if you are using the `daniel/read_hifld_grid` branch of PowerSimData, then you can pass `grid_model="hifld"` to create Grids using the data in that folder, and these Grids can be passed to any other function that needs them.

**Comment by danielolsen** [comment]
We were mistaken earlier, the parameter we want to set in the Grid constructor is actually `source`:
```python
electricity_grid = Grid("Texas", grid_model="hifld")
```
