### ISSUE TITLE
Python 3.9 is not supported by pyproj 2.6.1.post1

### ISSUE THREAD

**Issue by danielolsen** [Breakthrough-Energy/PreREISE#164]
Issue originally raised at https://github.com/Breakthrough-Energy/PreREISE/pull/163

pyproj 2.6.1.post1 documentation: https://pypi.org/project/pyproj/2.6.1.post1/

When upgrading from 1.x to 2.x, there were some significant changes, such that code that had previously run quickly was taking hours (see https://github.com/Breakthrough-Energy/PreREISE/pull/147, https://github.com/Breakthrough-Energy/PostREISE/pull/154). Hopefully, we will not run into such challenges going from 2.x to 3.x.

**Comment by jon-hagg** [comment]
Turns out it is not necessarily a compatibility issue - I'm able to install `pyproj==2.6.1.post1` in a python 3.9 environment with both pip and pipenv. Could be unresolvable in PreREISE due to other package constraints, or something else, but will need to do more digging.
