### ISSUE TITLE
HRRR data

### ISSUE THREAD

**Issue by yixingxu** [Breakthrough-Energy/PreREISE#176]
# :rocket:

- [ ] Is your feature request essential for your project?

### Describe the workflow you want to enable
Adding capability to download wind speed data from the High-Resolution Rapid Refresh service, to replace our current wind data source. 
Data source page: https://rapidrefresh.noaa.gov/hrrr/

### Describe your proposed implementation
This should provide a description of the feature request, e.g.:
Need help from software side to explore implementation

If applicable, try to write a docstring for the desired feature. To illustrate, if you would like to add a new function in a module, provide:
* the name of the function
* a description of the task accomplished by the function
* a list of the input and output parameters together with their types (e.g., `int`,
  `str`, `pandas.DataFrame`, etc.) and a short description of its/their meaning
 Need help from software side to explore

### Describe alternatives you've considered, if relevant
This should provide a description of any alternative solutions or features you've
considered.

### Additional context
Add any other context or screenshots in this section, e.g., a plot from an article you
believe would clearly communicate results.

**Comment by kasparm** [comment]
@yixingxu or research please provide data source location, details about data source (resolution) and specific values(variable name) to be extracted from the data source.
Is there any modeling needed from source to wind power profile used by the model?
Thanks for completing this request.

**Comment by rouille** [comment]
What should we do if 2016 data are not available? Do we need to reprocess the demand, hydro and solar to have the same year? What do we do if we cannot get demand, hydro, solar and wind data for the same year?

**Comment by yixingxu** [comment]
considering the other high priorities, we do not need to work on it in recent sprints. 
We need to do some research to answer Ben and Kaspar's questions.
