### ISSUE TITLE
Update solar profile generation to reflect that nrel-pysam can now handle leap years

### ISSUE THREAD

**Issue by danielolsen** [Breakthrough-Energy/PreREISE#254]
# :rocket:

- [ ] Is your feature request essential for your project?

### Describe the workflow you want to enable
I wish that `prereise.gather.solardata.nsrdb.sam` were simplified, to reflect changes in NREL-PySAM v2.2.2: "Leap year 2/29 date is now acceptable".

### Describe your proposed implementation
Refactor the `retrieve_data_blended` and `retrieve_data_individual` functions to avoid using two distinct datetime arrays (the real datetimes and the everything-but-leap-day datetimes), and remove the `generate_timestamps_without_leap_day` helper function. Inputs/outputs should remain the same, with the exception that the leap day power profiles will change to reflect actual February 29th weather, not just a copy of February 28th.

**Comment by rouille** [comment]
That was an ugly fix!

**Comment by danielolsen** [comment]
It looks like this may not be possible after all. SAM will now _accept_ weather files including leap year data (see https://github.com/NREL/pysam/blob/master/RELEASE.md#version-222-mar-19-2021--sam-20201129-revision-1-ssc-version-253), but the power outputs it _produces_ still do not contain leap days (see https://sam.nrel.gov/forum/forum-general/3722-accounting-for-daylight-saving-time-dst-in-electricity-rates.html#10448, or test for yourself).
