### ISSUE TITLE
Data Intake for balancing authority shapefile generation

### ISSUE THREAD

**Issue by limingzhou2004** [Breakthrough-Energy/PreREISE#269]
## Source
* Name: Balance area map
* Author:  HIFLD control area, ISO/RTO subregional maps
* Description: Zenodo provide the cleaned hourly load data for all control areas  and subregions. The CAs with subregional data are ISONE, NYISO, PJM, ERCO, CISO, SWPP, MISO.  The BA maps have some of the CAs , the seven ISO subregional maps, and zones.  The rest CAs not present in the current BA map are mapped to the current map. A mapping table from the CAs to the BA map has the fraction column, based on the overlapped area.  
* Source: HIFLD
* Exact source location:    
control area--   https://hifld-geoplatform.opendata.arcgis.com/datasets/geoplatform::control-areas-1/explore?location=29.801747%2C-84.928759%2C7.75
state boundary -- https://www.census.gov/geographies/mapping-files/time-series/geo/carto-boundary-file.html
PJM subregions -- https://www.monitoringanalytics.com/reports/PJM_State_of_the_Market/2018/2018-som-pjm-volume2-appendix.pdf
NYISO -- Downloaded from https://www.arcgis.com/home/item.html?id=6fd1de467b134f47a607721f23a69f0c
* Terms (if specified):  unlimited
### Destination
* Modifications to source files(s): new file remap_ba_area.py
* Location: prereise/gather/data/remap_ba_area

### General Purpose
The load data with better spatial resolution are mapped to the CA zones, subregions, and zones.

**Comment by danielolsen** [comment]
Let's focus this data intake on just the geographic information, and we can tackle the Zenodo/EIA load data in a follow-up.

Besides the HIFLD Control Areas shapefiles, which other data sources are we using?

Which branch has the script that translates source shapes to final shapes?

**Comment by danielolsen** [comment]
Closed via #270
