### ISSUE TITLE
Develop shapefiles for urban areas and rural areas for each state

### ISSUE THREAD

**Issue by BainanXia** [Breakthrough-Energy/PreREISE#273]
# :rocket:

- [x] Is your feature request essential for your project?

### Describe the workflow you want to enable
I wish I had a shapefile that defines the urban areas and rural area for each state within the U.S. note that there could be multiple urban areas within a state and the rest area forms the corresponding rural area(s).

### Describe your proposed implementation
- We have the urban area shapefile provided by our collaborators in `Breakthrough Energy Dropbox/BESExternalCollaborations/Transportation Electrification Modeling/urban_areas_shapefile` and there should be state tags somewhere within the shapefile, otherwise we will need to figure out with state boundary overlap.
- We will need to identify rural areas within each state based on the urban areas, they are complementary.

### Additional context
- Some urban areas are crossing state boundaries, which can be resolved with a state boundary overlay, i.e. split into two urban areas in different states.
- The resultant shapefile should cover entire contiguous USA without holes or overlappings.

**Comment by danielolsen** [comment]
Closed via #291.
